[package]
name = "tui"
version = "0.1.0"
edition = "2021"
default-run = "tui"
[dependencies]
db = { path = "../../lib/db" }
crossterm = "0.27.0"
lazy_static = "1.5.0"
ratatui = "0.27.0"
tui-input = "0.9.0"
rusqlite = "0.31.0"
