[package]
name = "tui_v2"
version = "0.1.0"
edition = "2021"

default-run = "tui_v2"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.28.1"
db = { path = "../../lib/db" }
random-string = "1.1.0"
ratatui = "0.28.0"
tui-input = "0.9.0"

